data:extend({
  {
    type = "simple-entity-with-owner",
    name = "stable-negative-space",
    alert_when_damaged = false,
    create_ghost_on_death = true,
    hide_resistances = true,
    healing_per_tick = 0.1,
    collision_box = { { -0.4, -0.4 }, { 0.4, 0.4 } },
    collision_mask = {
      layers = {
        water_tile = true,
        floor = true,
        object = true,
        is_lower_object = true,
      },
    },
    --created_smoke = {},  -- TODO: remove smoke.
    flags = {
      "not-rotatable",
      "placeable-player",
      "player-creation",
      "not-flammable",
      "not-upgradable",
      "not-in-kill-statistics",
    },
    hidden_in_factoriopedia = true,
    icon = "__negative_space__/graphics/icon.png",
    icon_size = 48,
    minable = { mining_time = 0.1 },
    placeable_by = { item = "negative-space", count = 1 },
    protected_from_tile_building = false,
    remove_decoratives = "false",
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    picture = {
      filename = "__negative_space__/graphics/icon.png",
      size = 48,
    },
  },
  {
    type = "simple-entity-with-owner",
    name = "unstable-negative-space",
    deconstruction_alternative = "stable-negative-space",
    alert_when_damaged = false,
    create_ghost_on_death = false,
    hide_resistances = true,
    healing_per_tick = 0.1,
    collision_box = { { -0.4, -0.4 }, { 0.4, 0.4 } },
    collision_mask = {
      layers = {
        water_tile = true,
        floor = true,
        object = true,
        is_lower_object = true,
      },
    },
    --created_smoke = {},  -- TODO: remove smoke.
    flags = {
      "not-rotatable",
      "placeable-player",
      "player-creation",
      "not-flammable",
      "not-upgradable",
      "not-in-kill-statistics",
    },
    hidden_in_factoriopedia = true,
    icon = "__negative_space__/graphics/icon.png",
    icon_size = 48,
    minable = { mining_time = 0.1 },
    -- It is not actually placeable, but this lets pipette give the right item.
    placeable_by = { item = "negative-space", count = 1 },
    protected_from_tile_building = false,
    remove_decoratives = "false",
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    picture = {
      filename = "__negative_space__/graphics/icon.png",
      size = 48,
    },
  },
})
